variables:
  CC: gcc
  CXX: g++

before_script:
  - echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
  - echo $0
  - pwd
  - ls
  - hostname
  - uname -a
  - lsb_release -a
  - env
  - cat /etc/apt/sources.list
  - ls /etc/apt/sources.list.d
  - which cmake
  - cmake --version
  - which $CC
  - $CC --version
  - which $CXX
  - $CXX --version
  - which ccache
  - ccache --version
  - ccache -s
  - ls -la /usr/lib/ccache
  - which swig3.0
  - swig3.0 -version
  - which javac
  - javac -version
  - echo "--------------------  END SYSTEM INFORMATION  --------------------"

stages:
  - configure
  - build

configure-cmake-3.0:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.0/bin/cmake
    - .ci/configure.sh

configure-cmake-3.1:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.1/bin/cmake
    - .ci/configure.sh

configure-cmake-3.2:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.2/bin/cmake
    - .ci/configure.sh

configure-cmake-3.3:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.3/bin/cmake
    - .ci/configure.sh

configure-cmake-3.4:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.4/bin/cmake
    - .ci/configure.sh

configure-cmake-3.5:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.5/bin/cmake
    - .ci/configure.sh

configure-cmake-3.6:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.6/bin/cmake
    - .ci/configure.sh

configure-cmake-3.7:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.7/bin/cmake
    - .ci/configure.sh

configure-cmake-3.8:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.8/bin/cmake
    - .ci/configure.sh

configure-cmake-3.9:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.9/bin/cmake
    - .ci/configure.sh

configure-cmake-3.10:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.10/bin/cmake
    - .ci/configure.sh

configure-cmake-3.11:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.11/bin/cmake
    - .ci/configure.sh

build-debian-testing:
  stage: build
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-debian-stretch:
  stage: build
  image: drdanz/yarp-builder-debian-stretch:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-ubuntu-bionic:
  stage: build
  image: drdanz/yarp-builder-ubuntu-bionic:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-ubuntu-artful:
  stage: build
  image: drdanz/yarp-builder-ubuntu-artful:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-ubuntu-xenial:
  stage: build
  image: drdanz/yarp-builder-ubuntu-xenial:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh
