before_script:
  - .ci/system_info.sh

stages:
  - configure
  - build-distro
  - build-compiler

configure-cmake-3_0:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.0/bin/cmake
    - .ci/configure.sh

configure-cmake-3_1:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.1/bin/cmake
    - .ci/configure.sh

configure-cmake-3_2:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.2/bin/cmake
    - .ci/configure.sh

configure-cmake-3_3:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.3/bin/cmake
    - .ci/configure.sh

configure-cmake-3_4:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.4/bin/cmake
    - .ci/configure.sh

configure-cmake-3_5:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.5/bin/cmake
    - .ci/configure.sh

configure-cmake-3_6:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.6/bin/cmake
    - .ci/configure.sh

configure-cmake-3_7:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.7/bin/cmake
    - .ci/configure.sh

configure-cmake-3_8:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.8/bin/cmake
    - .ci/configure.sh

configure-cmake-3_9:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.9/bin/cmake
    - .ci/configure.sh

configure-cmake-3_10:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.10/bin/cmake
    - .ci/configure.sh

configure-cmake-3_11:
  stage: configure
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cmake /opt/cmake-3.11/bin/cmake
    - .ci/configure.sh

build-debian-testing:
  stage: build-distro
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-debian-stretch:
  stage: build-distro
  image: drdanz/yarp-builder-debian-stretch:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-ubuntu-bionic:
  stage: build-distro
  image: drdanz/yarp-builder-ubuntu-bionic:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-ubuntu-artful:
  stage: build-distro
  image: drdanz/yarp-builder-ubuntu-artful:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-ubuntu-xenial:
  stage: build-distro
  image: drdanz/yarp-builder-ubuntu-xenial:latest
  script:
    - .ci/configure.sh
    - .ci/build.sh

build-gcc-6:
  stage: build-compiler
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set gcc /usr/bin/gcc-6
    - .ci/configure.sh
    - .ci/build.sh

build-gcc-7:
  stage: build-compiler
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set gcc /usr/bin/gcc-7
    - .ci/configure.sh
    - .ci/build.sh

build-gcc-8:
  stage: build-compiler
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set gcc /usr/bin/gcc-8
    - .ci/configure.sh
    - .ci/build.sh

build-clang-4_0:
  stage: build-compiler
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cc /usr/bin/clang
    - update-alternatives --set c++ /usr/bin/clang++
    - update-alternatives --set clang /lib/llvm-4.0/bin/clang
    - .ci/configure.sh
    - .ci/build.sh

build-clang-5_0:
  stage: build-compiler
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cc /usr/bin/clang
    - update-alternatives --set c++ /usr/bin/clang++
    - update-alternatives --set clang /lib/llvm-5.0/bin/clang
    - .ci/configure.sh
    - .ci/build.sh

build-clang-6_0:
  stage: build-compiler
  image: drdanz/yarp-builder-debian-testing:latest
  script:
    - update-alternatives --set cc /usr/bin/clang
    - update-alternatives --set c++ /usr/bin/clang++
    - update-alternatives --set clang /lib/llvm-6.0/bin/clang
    - .ci/configure.sh
    - .ci/build.sh
