analyzers:
 - cpplint: true
   include: ["*.cpp", "*.cc", "*.h", "*.hpp", "*.c"]
   path: ./src/
   filters: ["-", "+whitespace/tab", "+whitespace/end_of_line"]
   style: google # webkit | google

 - polysquare-cmake: true
   allowed: ["CMakeLists.txt"]

 - markdownlint: true
