analyzers:
 - cpplint: true
   path: ./src/
   filter: ["-whitespace"]
   style: google # webkit | google

 - polysquare-cmake: true
   allowed: ["CMakeLists.txt", "*.cmake"]

 - markdownlint: true

 - shellcheck: true
   interpreter: sh
