platform: linux

build:
 - mkdir build
 - cd build
 - cmake ..
 - make

test:
 - make test

analyzers:
 - cpplint: true
   include: ["*.cpp", "*.h", "*.hpp", "*.c"]
   path: ./src/
   filters:
   - -
   - +whitespace/tab
   - +whhitespace/end_of_line
   style: google # webkit | google

 - polysquare-cmake: true
   allowed: ["CMakeLists.txt"]

 - markdownlint: true
